### ISSUE TITLE
save_to_firestore

### ISSUE THREAD

**Issue by EarthShaping** [giasar/daticovid#3]
Where save_to_firestore is defined?

**Comment by giasar** [comment]
Hi @EarthShaping, thanks for the question. 

To be completely honest with you: I started this project thinking it was going to be something nobody really cared that much about so I spent no time making it accessible to other coders (the code is pretty badly organised, versioned and not documented at all). Last month I decided to remove code that saved the daily COVID-19 data to Firestore, since there was really no use in having stored records, and in doing that I forgot to update _populate.py_ with the modifications. So as of now save_to_firestore is not really defined anywhere. Mea culpa.

This is a good opportunity to make the necessary changes and also make the code more documented. I'm going to work on it immediately, starting from a fix to _populate.py_ which I'm going to link to this issue.

Thanks for the interest!
